apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensetracker-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expensetracker
  template:
    metadata:
      labels:
        app: expensetracker
    spec:
      containers:
        - name: expensetracker
          image: loveisall/expensetracker:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: expensetracker-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30002
  selector:
      app: expensetracker
